### ISSUE TITLE
mruby/c のIDEを作ってみませんか？

### ISSUE THREAD

**Issue by kojix2** [spoolkitamura/rbpad3#1]
こんにちは。kojix2と申します。

このプロジェクトを発見しました。
インターネットで検索したところ、この作品が、中高生国際プログラミングコンテストの受賞作品であることを知りました。
https://www.ruby-procon.net/study/docs/2020072300080/

もしよかったら、このrbpadを改造して
mruby/c のIDEを作ってみませんか？

https://www.sjc-inc.co.jp/service/rboard
https://www.s-itoc.jp/activity/research/mrubyc/mrubyc_download/

お忙しいと思いますが、もしよかったらご検討ください。

**Comment by spoolkitamura** [comment]
こんにちは。
ご連絡ありがとうございます。

rbpadは「中高生国際プログラミングコンテスト」の受賞作品ではなくて、
「第10回フクオカRuby大賞」で Salesforce賞をいただいた作品になります。
[http://www.digitalfukuoka.jp/topics/116](http://www.digitalfukuoka.jp/topics/116)

ただ、取り組みのきっかけは
「中高生をはじめ、初心者でもできるだけ簡単に Rubyを始められるように」という思いからでした。
(そのような路線で、その後も「フクオカ Ruby大賞」には毎回参加させていただいています...)

mrubyや mruby/cはほんの少し概要をかじった程度で、
rbpadを改造して mruby/cの IDEができるものなのかどうかもよくわかっていないレベルです。

ほぼゼロからの勉強になりますが、ご提案をきっかけにして検討してみたいと思います。


なお、直近の「フクオカRuby大賞」には、
micro:bitという英BBCが開発した教育向けのマイコンボードを Rubyで使うための
クラスライブラリで応募しました。

シリアル通信で Rubyから micro:bitを操作する簡単な仕組みのものなのですが、
審査員の方々からは「mrubyでもぜひ」とコメントをいただいたところでした。

いろいろと情報交換などさせていただけると幸いです。
よろしくお願いします。

**Comment by kojix2** [comment]
すみません。中高生の人が素晴らしいツールを作って公開しているのかな？
若い才能はすごいなーと勘違いしてしまいまして。（苦笑）。失礼しました。

丁度すでにmicro:bitというマイコンボードを扱っていらっしゃるところだったのですね。

私はコンピュータ業界の人間ではなく、mrubyやmruby/cは何もわからないです。
しかし最近RBoardで遊んでいて、mruby/cのIDEがオープンソースではなく、しかもWindows版とMac版しか公開されてないことに気がつき、ここが不便だと思いました。

以前にgtk3の利用状況などを調べていて、その時にrbpad の存在を知っていました。
もしもIDEを自作するならrbpadの改造するのがいいかな、と思ったので試しにissueに書き込んだのでした。

オープンソースのプロジェクトを維持するのは簡単ではなく、楽なことばかりではないと存じております。
しかし、rbpad3はよくできているので、もしもmruby/c のIDEということになれば、利用する人は一定数いるのではないかと思います。すでにmicro:bitに取り組まれているということなので、いずれmrubyやmruby/cに取り組む機会はあるのではないかなと思います。その際に、もしよろしかったらぜひ作ってみてください。

よろしくお願いします。
